"""Server-side mock fixtures for Life modules."""

MOCK_MODULE_RECORDS = {
    'moments': [
        {
            'id': 'mock-moment-1',
            'type': '记忆',
            'icon': '◌',
            'time': '21:40',
            'date': '2026-05-11',
            'title': '和老朋友重逢',
            'copy': '两年没见的大学室友，从下午聊到深夜，发现彼此都变得更松弛了。',
            'location': '本月值得记住',
            'people': ['张敏', '李想'],
            'mood': '温暖',
            'photos': ['photo-cafe', 'photo-night'],
            'tags': ['记忆', '朋友', '本月值得记住'],
            'linkedView': 'monthly',
        },
        {
            'id': 'mock-moment-2',
            'type': '健康',
            'icon': '♡',
            'time': '07:10',
            'date': '2026-05-10',
            'title': '健康与身体：年度体检完成',
            'copy': '指标整体正常，医生建议继续保持运动，减少久坐。',
            'location': '健康与身体',
            'people': [],
            'mood': '安心',
            'photos': ['photo-office'],
            'tags': ['健康', '身体信号'],
            'linkedView': 'health',
        },
        {
            'id': 'mock-moment-3',
            'type': '项目',
            'icon': '▤',
            'time': '16:00',
            'date': '2026-05-09',
            'title': '项目与目标：个人网站首页评审',
            'copy': '主视觉方向确定，下一步补齐作品集详情页和联系表单。',
            'location': '项目与目标',
            'people': ['May', '陈昊'],
            'mood': '充实',
            'photos': ['photo-office', 'photo-book'],
            'tags': ['项目', '作品集', '工作'],
            'linkedView': 'projects',
        },
    ],
    'axis': [
        {
            'id': 'mock-axis-2026-travel',
            'year': '2026',
            'season': '春',
            'day': '03-18',
            'title': '杭州慢旅行',
            'desc': '三天两晚，重点看自然和步行路线。',
            'type': '旅行',
            'icon': 'travel',
            'place': '浙江 · 杭州',
            'date': '2026-03-18',
            'photos': ['photo-river'],
            'people': 2,
        },
        {
            'id': 'mock-axis-2026-project',
            'year': '2026',
            'season': '夏',
            'day': '06-22',
            'title': '个人站点改版上线',
            'desc': '完成信息架构重整和作品集发布。',
            'type': '项目',
            'icon': 'project',
            'place': '上海',
            'date': '2026-06-22',
            'photos': ['photo-office'],
            'people': 1,
        },
        {
            'id': 'mock-axis-2026-health',
            'year': '2026',
            'season': '秋',
            'day': '09-08',
            'title': '完成半马训练周期',
            'desc': '连续 12 周训练，心肺耐力明显提升。',
            'type': '健康',
            'icon': 'health',
            'place': '上海 · 滨江',
            'date': '2026-09-08',
            'photos': ['photo-garden'],
            'people': 0,
        },
        {
            'id': 'mock-axis-2026-relationship',
            'year': '2026',
            'season': '冬',
            'day': '12-12',
            'title': '家庭年末团聚',
            'desc': '和父母姐姐完成年度家庭复盘与计划。',
            'type': '关系',
            'icon': 'relationship',
            'place': '成都',
            'date': '2026-12-12',
            'photos': ['photo-cafe'],
            'people': 4,
        },
        {
            'id': 'mock-axis-2025-travel',
            'year': '2025',
            'season': '春',
            'day': '04-06',
            'title': '苏州园林周末行',
            'desc': '短途放松，梳理下一阶段生活节奏。',
            'type': '旅行',
            'icon': 'travel',
            'place': '江苏 · 苏州',
            'date': '2025-04-06',
            'photos': ['photo-garden'],
            'people': 1,
        },
        {
            'id': 'mock-axis-2025-project',
            'year': '2025',
            'season': '夏',
            'day': '07-15',
            'title': '摄影作品集首版完成',
            'desc': '完成 30 张精选作品与文案撰写。',
            'type': '项目',
            'icon': 'project',
            'place': '上海',
            'date': '2025-07-15',
            'photos': ['photo-office'],
            'people': 2,
        },
        {
            'id': 'mock-axis-2025-health',
            'year': '2025',
            'season': '秋',
            'day': '10-09',
            'title': '年度体检达标',
            'desc': '血脂与睡眠指标回到健康区间。',
            'type': '健康',
            'icon': 'health',
            'place': '上海',
            'date': '2025-10-09',
            'photos': ['photo-office'],
            'people': 0,
        },
        {
            'id': 'mock-axis-2025-relationship',
            'year': '2025',
            'season': '冬',
            'day': '12-21',
            'title': '和老友恢复稳定联系',
            'desc': '建立每月一次深度交流的固定节奏。',
            'type': '关系',
            'icon': 'relationship',
            'place': '线上',
            'date': '2025-12-21',
            'photos': ['photo-night'],
            'people': 2,
        },
        {
            'id': 'mock-axis-2024-travel',
            'year': '2024',
            'season': '春',
            'day': '03-30',
            'title': '厦门海边独处周末',
            'desc': '做了一次低信息密度的断联休息。',
            'type': '旅行',
            'icon': 'travel',
            'place': '福建 · 厦门',
            'date': '2024-03-30',
            'photos': ['photo-river'],
            'people': 0,
        },
        {
            'id': 'mock-axis-2024-project',
            'year': '2024',
            'season': '夏',
            'day': '06-11',
            'title': '副业验证 MVP 发布',
            'desc': '完成第一版功能闭环并拿到首批反馈。',
            'type': '项目',
            'icon': 'project',
            'place': '上海',
            'date': '2024-06-11',
            'photos': ['photo-book'],
            'people': 1,
        },
        {
            'id': 'mock-axis-2024-health',
            'year': '2024',
            'season': '秋',
            'day': '09-17',
            'title': '开始规律力量训练',
            'desc': '每周三次，重点改善久坐带来的不适。',
            'type': '健康',
            'icon': 'health',
            'place': '上海',
            'date': '2024-09-17',
            'photos': ['photo-garden'],
            'people': 0,
        },
        {
            'id': 'mock-axis-2024-relationship',
            'year': '2024',
            'season': '冬',
            'day': '11-26',
            'title': '亲密关系边界重建',
            'desc': '通过持续沟通形成更稳定的相处方式。',
            'type': '关系',
            'icon': 'relationship',
            'place': '上海',
            'date': '2024-11-26',
            'photos': ['photo-cafe'],
            'people': 2,
        },
        {
            'id': 'mock-axis-2023-travel',
            'year': '2023',
            'season': '春',
            'day': '04-14',
            'title': '云南徒步旅行',
            'desc': '第一次长线路徒步，节奏慢下来很多。',
            'type': '旅行',
            'icon': 'travel',
            'place': '云南',
            'date': '2023-04-14',
            'photos': ['photo-mountain'],
            'people': 3,
        },
        {
            'id': 'mock-axis-2023-project',
            'year': '2023',
            'season': '夏',
            'day': '07-07',
            'title': '工作流自动化改造',
            'desc': '把重复记录流程自动化，节省大量时间。',
            'type': '项目',
            'icon': 'project',
            'place': '上海',
            'date': '2023-07-07',
            'photos': ['photo-office'],
            'people': 2,
        },
        {
            'id': 'mock-axis-2023-health',
            'year': '2023',
            'season': '秋',
            'day': '09-29',
            'title': '睡眠修复计划完成',
            'desc': '作息从凌晨调整到 23:30 前入睡。',
            'type': '健康',
            'icon': 'health',
            'place': '上海',
            'date': '2023-09-29',
            'photos': ['photo-night'],
            'people': 0,
        },
        {
            'id': 'mock-axis-2023-relationship',
            'year': '2023',
            'season': '冬',
            'day': '12-03',
            'title': '与家人建立固定通话日',
            'desc': '固定每周一次电话，关系稳定升温。',
            'type': '关系',
            'icon': 'relationship',
            'place': '线上',
            'date': '2023-12-03',
            'photos': ['photo-book'],
            'people': 3,
        },
    ],
    'decisions': [
        {
            'id': 'mock-decision-job-change',
            'status': '待复盘',
            'title': '是否换工作？',
            'date': '2026-05-18',
            'category': '职业发展',
            'choice': '接受新机会并换工作',
            'confidence': 82,
            'background': '当前岗位稳定，但成长空间和薪酬增幅有限；新机会在业务影响力和发展路径上更匹配长期目标。',
            'reason': ['新岗位职责更聚焦核心能力。', '团队资源更成熟，能更快放大产出。', '薪酬与成长曲线更符合预期。'],
            'risks': ['新团队磨合期压力更高。', '试用期内目标交付节奏更紧。'],
            'options': [
                ['留在原公司', '保持稳定', '上海', '风险低', '成长速度一般'],
                ['换到新公司', '接受 offer', '上海', '适应成本', '成长速度更快'],
            ],
            'reviewDate': '2026-11-18',
            'result': '已在新公司工作中，持续观察 3 个月的匹配度。',
        },
        {
            'id': 'mock-decision-1',
            'status': '冷却中',
            'title': '是否继续租现在的房子？',
            'date': '2026-05-06',
            'category': '居住',
            'choice': '暂缓决定',
            'confidence': 55,
            'background': '当前房子通勤便利、生活圈成熟，但续租租金上涨明显。',
            'reason': ['先确认房东最终报价。', '对比同区域两套备选房源。'],
            'risks': ['拖延太久可能错过合适房源。'],
            'options': [
                ['继续续租', '保持现状', '徐汇', '租金上涨 12%', '稳定便利'],
                ['搬到新房', '重新选择', '静安/长宁', '押金 + 搬家成本', '可能更舒适'],
            ],
            'reviewDate': '2026-06-06',
            'result': '仍在收集信息，暂不做最终决定。',
        },
        {
            'id': 'mock-decision-2',
            'status': '待复盘',
            'title': '是否减少社交媒体使用？',
            'date': '2026-04-05',
            'category': '健康',
            'choice': '限制到每天 30 分钟',
            'confidence': 76,
            'background': '最近信息摄入过多，影响睡眠和专注力。',
            'reason': ['晚上刷手机会推迟入睡。', '减少碎片信息可以改善专注。'],
            'risks': ['可能错过朋友动态和行业信息。'],
            'options': [
                ['严格限制', '每天 30 分钟', '手机', '0', '专注力提升'],
                ['保持现状', '自由使用', '手机', '0', '无切换成本'],
            ],
            'reviewDate': '2026-05-20',
            'result': '第一阶段有效，晚间睡眠有所改善。',
        },
    ],
    'moods': [
        {
            'id': 'mock-mood-1',
            'year': 2026,
            'month': 4,
            'day': 12,
            'date': '2026-05-12',
            'weekday': '周二',
            'time': '08:40',
            'score': 82,
            'weather': '晴朗',
            'sleep': 7.6,
            'pressure': 26,
            'energy': 86,
            'feeling': '轻快',
            'note': '早起跑步后状态很好，工作推进顺畅。',
            'tags': ['运动', '专注', '测试数据'],
        },
        {
            'id': 'mock-mood-2',
            'year': 2026,
            'month': 4,
            'day': 13,
            'date': '2026-05-13',
            'weekday': '周三',
            'time': '22:10',
            'score': 58,
            'weather': '多云',
            'sleep': 6.1,
            'pressure': 52,
            'energy': 54,
            'feeling': '疲惫',
            'note': '会议偏多，晚上注意力下滑。',
            'tags': ['会议', '工作', '测试数据'],
        },
        {
            'id': 'mock-mood-3',
            'year': 2026,
            'month': 4,
            'day': 14,
            'date': '2026-05-14',
            'weekday': '周四',
            'time': '21:30',
            'score': 46,
            'weather': '阴雨',
            'sleep': 5.7,
            'pressure': 66,
            'energy': 45,
            'feeling': '烦躁',
            'note': '临时需求打乱节奏，情绪起伏明显。',
            'tags': ['加班', '变更', '测试数据'],
        },
        {
            'id': 'mock-mood-4',
            'year': 2026,
            'month': 4,
            'day': 15,
            'date': '2026-05-15',
            'weekday': '周五',
            'time': '23:05',
            'score': 24,
            'weather': '低落',
            'sleep': 4.9,
            'pressure': 79,
            'energy': 31,
            'feeling': '焦虑',
            'note': '临近节点压力大，睡前仍在想工作。',
            'tags': ['截止日', '压力', '测试数据'],
        },
        {
            'id': 'mock-mood-5',
            'year': 2026,
            'month': 4,
            'day': 16,
            'date': '2026-05-16',
            'weekday': '周六',
            'time': '19:20',
            'score': 64,
            'weather': '微晴',
            'sleep': 8.0,
            'pressure': 38,
            'energy': 67,
            'feeling': '放松',
            'note': '和朋友吃饭散步，恢复感不错。',
            'tags': ['社交', '休息', '测试数据'],
        },
        {
            'id': 'mock-mood-6',
            'year': 2026,
            'month': 4,
            'day': 17,
            'date': '2026-05-17',
            'weekday': '周日',
            'time': '20:50',
            'score': 71,
            'weather': '晴朗',
            'sleep': 7.4,
            'pressure': 34,
            'energy': 73,
            'feeling': '平静',
            'note': '做了下周计划，内心更有秩序。',
            'tags': ['规划', '复盘', '测试数据'],
        },
        {
            'id': 'mock-mood-7',
            'year': 2026,
            'month': 4,
            'day': 18,
            'date': '2026-05-18',
            'weekday': '周一',
            'time': '18:35',
            'score': 76,
            'weather': '微晴',
            'sleep': 6.9,
            'pressure': 42,
            'energy': 75,
            'feeling': '笃定',
            'note': '入职新岗位第一天，节奏紧但方向明确。',
            'tags': ['换工作', '新开始', '测试数据'],
        },
        {
            'id': 'mock-mood-8',
            'year': 2026,
            'month': 4,
            'day': 19,
            'date': '2026-05-19',
            'weekday': '周二',
            'time': '22:25',
            'score': 62,
            'weather': '多云',
            'sleep': 6.4,
            'pressure': 49,
            'energy': 58,
            'feeling': '谨慎',
            'note': '适应新工具链，投入成本偏高。',
            'tags': ['适应期', '学习', '测试数据'],
        },
        {
            'id': 'mock-mood-9',
            'year': 2026,
            'month': 4,
            'day': 20,
            'date': '2026-05-20',
            'weekday': '周三',
            'time': '21:40',
            'score': 55,
            'weather': '阴天',
            'sleep': 6.0,
            'pressure': 57,
            'energy': 52,
            'feeling': '紧绷',
            'note': '需求评审反复，沟通成本上升。',
            'tags': ['沟通', '评审', '测试数据'],
        },
        {
            'id': 'mock-mood-10',
            'year': 2026,
            'month': 4,
            'day': 21,
            'date': '2026-05-21',
            'weekday': '周四',
            'time': '23:15',
            'score': 33,
            'weather': '低落',
            'sleep': 5.1,
            'pressure': 72,
            'energy': 36,
            'feeling': '沮丧',
            'note': '方案被否后有点失落，晚间恢复较慢。',
            'tags': ['反馈', '挫折', '测试数据'],
        },
        {
            'id': 'mock-mood-11',
            'year': 2026,
            'month': 4,
            'day': 22,
            'date': '2026-05-22',
            'weekday': '周五',
            'time': '20:10',
            'score': 68,
            'weather': '微晴',
            'sleep': 7.1,
            'pressure': 41,
            'energy': 69,
            'feeling': '释然',
            'note': '和同事对齐后，问题拆解清楚了。',
            'tags': ['协作', '推进', '测试数据'],
        },
        {
            'id': 'mock-mood-12',
            'year': 2026,
            'month': 4,
            'day': 23,
            'date': '2026-05-23',
            'weekday': '周六',
            'time': '17:45',
            'score': 74,
            'weather': '晴朗',
            'sleep': 8.2,
            'pressure': 29,
            'energy': 78,
            'feeling': '满足',
            'note': '白天户外活动，身心都在回升。',
            'tags': ['户外', '休闲', '测试数据'],
        },
        {
            'id': 'mock-mood-13',
            'year': 2026,
            'month': 4,
            'day': 24,
            'date': '2026-05-24',
            'weekday': '周日',
            'time': '21:00',
            'score': 60,
            'weather': '多云',
            'sleep': 7.0,
            'pressure': 47,
            'energy': 61,
            'feeling': '平稳',
            'note': '提前整理周计划，情绪比较稳定。',
            'tags': ['整理', '计划', '测试数据'],
        },
        {
            'id': 'mock-mood-14',
            'year': 2026,
            'month': 4,
            'day': 25,
            'date': '2026-05-25',
            'weekday': '周一',
            'time': '09:30',
            'score': 84,
            'weather': '晴朗',
            'sleep': 7.8,
            'pressure': 32,
            'energy': 85,
            'feeling': '期待',
            'note': '新一周开始，节奏和目标都比较清晰。',
            'tags': ['目标', '晨间状态', '测试数据'],
        },
    ],
    'relationships': [
        {
            'id': 'mock-relationship-1',
            'name': '姐姐',
            'role': '姐姐',
            'group': '家人',
            'last': '2 周前',
            'channel': '微信',
            'score': 64,
            'nextDate': '2026-06-01',
            'trend': [44, 50, 56, 52, 60, 64],
            'dates': ['生日 1988-08-15'],
            'notes': ['她最近工作很忙，计划周末视频。'],
            'memories': ['厦门旅行', '一起插花'],
        },
        {
            'id': 'mock-relationship-2',
            'name': '陈昊',
            'role': '设计伙伴',
            'group': '同事',
            'last': '1 天前',
            'channel': '飞书',
            'score': 83,
            'nextDate': '2026-05-30',
            'trend': [68, 72, 74, 80, 78, 83],
            'dates': ['合作开始 2026-01-08'],
            'notes': ['讨论了首页动效和作品集排版。'],
            'memories': ['官网评审', '设计冲刺'],
        },
        {
            'id': 'mock-relationship-3',
            'name': '李想',
            'role': '前同事',
            'group': '朋友',
            'last': '20 天前',
            'channel': '微信',
            'score': 68,
            'nextDate': '2026-05-28',
            'trend': [55, 50, 62, 58, 63, 68],
            'dates': ['认识纪念日 2019-06-12'],
            'notes': ['约了下周咖啡，聊近况和职业选择。'],
            'memories': ['产品发布', '深夜加班'],
        },
        {
            'id': 'mock-relationship-4',
            'name': 'Emma',
            'role': '旅行伙伴',
            'group': '朋友',
            'last': '昨天',
            'channel': '微信',
            'score': 86,
            'nextDate': '2026-05-31',
            'trend': [60, 68, 76, 82, 80, 86],
            'dates': ['第一次旅行 2024-05-04'],
            'notes': ['一起规划夏天的短途旅行。'],
            'memories': ['杭州西湖', '南京书店'],
        },
        {
            'id': 'mock-relationship-5',
            'name': '周老师',
            'role': '人生导师',
            'group': '重要联系人',
            'last': '28 天前',
            'channel': '电话',
            'score': 85,
            'nextDate': '2026-06-24',
            'trend': [76, 80, 78, 84, 82, 85],
            'dates': ['第一次咨询 2022-03-18'],
            'notes': ['提醒我在重大选择里区分事实和恐惧。'],
            'memories': ['年度复盘', '职业咨询'],
        },
        {
            'id': 'mock-relationship-6',
            'name': '妈妈',
            'role': '母亲',
            'group': '家人',
            'last': '今天',
            'channel': '微信',
            'score': 92,
            'nextDate': '2026-05-30',
            'trend': [52, 70, 62, 84, 76, 92],
            'dates': ['生日 1958-06-21', '母亲节 每年 5 月第二个周日'],
            'notes': ['讨论端午节回家的计划，想带她去拍照。'],
            'memories': ['2024 春节', '杭州之旅'],
        },
        {
            'id': 'mock-relationship-7',
            'name': '阿木',
            'role': '摄影伙伴',
            'group': '朋友',
            'last': '6 天前',
            'channel': '微信',
            'score': 76,
            'nextDate': '2026-06-04',
            'trend': [58, 62, 66, 74, 70, 76],
            'dates': ['第一次拍摄 2023-04-02'],
            'notes': ['约了下次外拍路线。'],
            'memories': ['西湖拍摄', '器材讨论'],
        },
    ],
    'wishes': [
        {
            'id': 'mock-wish-1',
            'status': '愿望冷却中',
            'category': '生活',
            'name': '周末陶艺体验课',
            'reason': '想给自己一段不用屏幕的创作时间。',
            'days': 9,
            'due': '2026-06-03',
            'desire': 61,
            'price': '¥268',
            'alternatives': ['先在家做手账', '找免费的城市活动'],
            'plan': ['确认课程时间', '问 Emma 是否一起去'],
            'photo': 'photo-book',
        },
        {
            'id': 'mock-wish-2',
            'status': '可以决定',
            'category': '健康',
            'name': '买一张游泳月卡',
            'reason': '希望用低冲击运动改善肩颈和睡眠。',
            'days': 0,
            'due': '2026-05-25',
            'desire': 74,
            'price': '¥699',
            'alternatives': ['继续跑步', '每周去单次票'],
            'plan': ['确认泳池距离', '周末试游一次'],
            'photo': 'photo-river',
        },
        {
            'id': 'mock-wish-3',
            'status': '已放弃',
            'category': '数码',
            'name': 'iPad Pro 11 英寸',
            'reason': '一时冲动，复盘后发现实际使用场景不多。',
            'days': 0,
            'due': '2026-05-11',
            'desire': 28,
            'price': '¥6,799',
            'alternatives': ['继续使用电脑', '先借朋友设备短期测试'],
            'plan': ['已放弃，半年后再看是否有持续需求'],
            'photo': 'photo-office',
        },
        {
            'id': 'mock-wish-4',
            'status': '已实现',
            'category': '关系',
            'name': '给妈妈做一本照片书',
            'reason': '把过去几年的合照整理成一份能长期留存的礼物。',
            'days': 0,
            'due': '2026-05-16',
            'desire': 91,
            'price': '¥268',
            'alternatives': ['线上相册', '打印精选照片'],
            'plan': ['已完成并在家庭聚会当天送出'],
            'photo': 'photo-cafe',
        },
    ],
    'monthly': [
        {
            'id': 'mock-monthly-state',
            'bookmarked': {'2026-05': True},
            'reports': {},
            'archived': {},
            'letters': {},
            'quotes': {'2026-05': '测试数据来自服务器端 mock fixture。'},
            'summaries': {},
        },
    ],
    'watch': [
        {
            'id': 'mock-watch-2024-1',
            'kind': 'movie',
            'title': '无尽之境',
            'year': 2024,
            'month': 0,
            'date': '2024-01-12',
            'rating': 8.6,
            'review': '世界观完整，镜头调度很稳。',
            'tags': ['科幻', '电影'],
            'finished': True,
            'progress': '',
            'duration': '2小时06分',
            'cover': 'photo-mountain',
        },
        {
            'id': 'mock-watch-2024-2',
            'kind': 'series',
            'title': '雾中来客',
            'year': 2024,
            'month': 1,
            'date': '2024-02-28',
            'rating': 8.7,
            'review': '悬疑线抓人，反转节奏控制得很好。',
            'tags': ['悬疑', '剧集'],
            'finished': True,
            'progress': '已看完',
            'duration': '46分钟/集',
            'cover': 'photo-night',
        },
        {
            'id': 'mock-watch-2024-3',
            'kind': 'movie',
            'title': '河畔的午后',
            'year': 2024,
            'month': 2,
            'date': '2024-03-15',
            'rating': 8.1,
            'review': '慢节奏但治愈感很强。',
            'tags': ['治愈', '电影'],
            'finished': True,
            'progress': '',
            'duration': '1小时38分',
            'cover': 'photo-river',
        },
        {
            'id': 'mock-watch-2025-1',
            'kind': 'movie',
            'title': '宇宙尽头小镇',
            'year': 2025,
            'month': 0,
            'date': '2025-01-05',
            'rating': 8.2,
            'review': '设定有趣，情感线也成立。',
            'tags': ['科幻', '电影'],
            'finished': True,
            'progress': '',
            'duration': '2小时14分',
            'cover': 'photo-night',
        },
        {
            'id': 'mock-watch-2025-2',
            'kind': 'series',
            'title': '光的孩子',
            'year': 2025,
            'month': 1,
            'date': '2025-02-14',
            'rating': 8.5,
            'review': '人物关系细腻，家庭戏很有共鸣。',
            'tags': ['家庭', '剧集'],
            'finished': True,
            'progress': '已看完',
            'duration': '42分钟/集',
            'cover': 'photo-cafe',
        },
        {
            'id': 'mock-watch-2025-3',
            'kind': 'movie',
            'title': '雪山记',
            'year': 2025,
            'month': 2,
            'date': '2025-03-02',
            'rating': 8.8,
            'review': '摄影非常出色，情绪铺垫很稳。',
            'tags': ['冒险', '电影'],
            'finished': True,
            'progress': '',
            'duration': '2小时01分',
            'cover': 'photo-mountain',
        },
        {
            'id': 'mock-watch-1',
            'kind': 'series',
            'title': '长夜电台',
            'year': 2026,
            'month': 8,
            'date': '2026-09-16',
            'rating': 8.1,
            'review': '整体稳定，台词有亮点。',
            'tags': ['悬疑', '剧集'],
            'finished': False,
            'progress': '看到 S01E04',
            'duration': '44分钟/集',
            'cover': 'photo-night',
        },
        {
            'id': 'mock-watch-2',
            'watchState': 'want',
            'kind': 'movie',
            'title': '银色公路',
            'year': 2026,
            'month': 10,
            'date': '2026-11-04',
            'rating': 8.0,
            'review': '朋友推荐，准备下月看。',
            'tags': ['想看', '电影'],
            'finished': True,
            'progress': '',
            'duration': '1小时52分',
            'cover': 'photo-night',
        },
    ],
    'projects': [
        {
            'id': 'mock-project-1',
            'name': '月度生活报告生成器',
            'progress': 42,
            'status': '摘要模板还需要打磨',
            'next': '补齐情绪和关系模块的摘要规则',
            'people': '个人项目',
        },
        {
            'id': 'mock-project-2',
            'name': '城市散步地图',
            'progress': 73,
            'status': '路线素材足够，缺少文字整理',
            'next': '完成徐汇滨江路线说明',
            'people': '与 Emma 协作',
        },
    ],
    'health': [
        {
            'id': 'mock-health-1',
            'name': '饮水',
            'value': '1.8 L',
            'note': '比上周稳定，下午咖啡减少后心悸也减少。',
        },
        {
            'id': 'mock-health-2',
            'name': '颈椎拉伸',
            'value': '完成 2 次',
            'note': '久坐后拉伸能明显缓解紧绷。',
        },
    ],
    'resources': [
        {
            'id': 'mock-resource-1',
            'name': '照片素材',
            'value': '186 张',
            'meta': '旅行、家人、城市散步、作品集候选',
        },
        {
            'id': 'mock-resource-2',
            'name': '月报归档',
            'value': '8 份',
            'meta': '服务器端 mock 归档数据',
        },
    ],
}
